### PR TITLE
Token and password login example

### LINKED ISSUE #86: Create an example for password and token based auth at the same time
As suggested in https://github.com/maxcountryman/axum-login/discussions/85 it would be a nice idea to have an example for situations where one would like to authenticate a user with two different secrets - a token a and a password.

### PR DESCRIPTION
**Pull request by czocher**
Implement an example showing how to login user with two different secrets (a token and a password in this case).

Closes #86.

### CODE REVIEW

**Comment by maxcountryman** [comment]
Thanks for putting this together.

I think we can merge it as-is but I also wonder if it'd be helpful to demonstrate a route which accepts either a token or a password?

**Comment by alexhumphreys** [comment]
> a route which accepts either a token or a password

For what it's worth, I'd find this example useful!

**Comment by maxcountryman** [comment]
I think we should merge it then and we can come back to it or add additional examples later as new use cases arise.

**Comment by Markusdreyer** [comment]
Why was this PR closed? I found the example useful

**Comment by maxcountryman** [comment]
@Markusdreyer the API of this crate has changed somewhat significantly.

Please take a look at the new examples.

**Pull request closed without merging**
