### PR TITLE
expose sqlx_store::SqlxStore

### PR DESCRIPTION
**Pull request by beckend**
https://github.com/maxcountryman/axum-login/issues/25

### CODE REVIEW

**Comment by beckend** [comment]
I would need with the docs please.

**Comment by maxcountryman** [comment]
I can't edit the PR directly, but you can pull in [these commits](https://github.com/maxcountryman/axum-login/tree/pr-31) if you like.

**Comment by beckend** [comment]
Now it's the examples.

**Comment by maxcountryman** [comment]
cargo fmt should address the formatting issue.

**Pull request merged**
