### PR TITLE
migrate to lazy sessions

### PR DESCRIPTION
**Pull request by maxcountryman**
This leverages lazy sessions as provided by tower-sessions.

### CODE REVIEW

**Comment by maxcountryman** [comment]
Please see [tower-sessions](https://github.com/maxcountryman/tower-sessions/pull/112) for pending upstream changes towards lazy sessions.

**Comment by maxcountryman** [comment]
Sorry for the ping @czocher: I wonder if you have any thoughts or concerns, even if only at a high level, before we commit to this direction?

**Comment by maxcountryman** [comment]
If there aren't any concerns here, I'm planning to move forward with this upstream and likewise with this PR.

**Comment by czocher** [comment]
Seems like a good idea, but wouldn't you like to merge them in `tower-sessions` first and release it?

**Comment by maxcountryman** [comment]
Yes, we'll publish a tower-sessions release beforehand. Before doing so, I want to make sure we agree this change to that API is okay.

**Pull request merged**
