### PR TITLE
Make role_bounds optional to require just login

### LINKED ISSUE #66: No role on user results in logging in with role bounds?
I noticed this:

https://github.com/maxcountryman/axum-login/blob/7e8f0ef44c483d3f8bab819b02c40d146411ea3f/axum-login/src/auth.rs#L159-L165

This returns true if a user's role is `None` which means this check will authorize the user:

https://github.com/maxcountryman/axum-login/blob/7e8f0ef44c483d3f8bab819b02c40d146411ea3f/axum-login/src/auth.rs#L212

### PR DESCRIPTION
**Pull request by epilys**
Closes #66

### CODE REVIEW

**Comment by maxcountryman** [comment]
Github is complaining about a merge conflict.

**Comment by epilys** [comment]
@maxcountryman will fix tomorrow. Do you think this is correct btw? I hope I didn't miss anything.

**Comment by maxcountryman** [comment]
@epilys thanks. As far as correctness: I think so, it's helpful to have the test cases, so thank you for adding those.

**Comment by maxcountryman** [comment]
Thanks, @epilys!

**Pull request merged**
