### PR TITLE
Use associated type instead of eyre for error message

### PR DESCRIPTION
**Pull request by iamsauravsharma**
~Use thiserror instead of eyre so error can be handled by library user. [https://docs.rs/eyre/latest/eyre/#comparison-to-thiserror](https://docs.rs/eyre/latest/eyre/#comparison-to-thiserror) for more information~ Use trait type instead of using eyre for error message

### CODE REVIEW

**Review by epilys — CHANGES_REQUESTED** [review]
This is useful because I also hit this problem when I was writing some stuff with `axum-login`

**Review by epilys — APPROVED** [review]

**Comment by iamsauravsharma** [comment]
I have added support for associated type Error without using both thiserror and eyre

**Comment by maxcountryman** [comment]
Thanks. Do you mind also updating the [change log](https://github.com/maxcountryman/axum-login/blob/main/CHANGELOG.md)?

**Comment by iamsauravsharma** [comment]
I have added changelog under unreleased header for PR

**Pull request merged**
