### PR TITLE
Integration tests setup

### PR DESCRIPTION
**Pull request by czotomo**
- major: directory structure rework to allow for easy installation of the package for testing purposes
- docker-compose file with Postgres and Mysql
- migrations creating test users table
- fixture with random user to use in tests

This PR doesn't really contain a lot of tests, the paramount goal was to setup a framework of sorts to allow writing such tests in the first place.

### CODE REVIEW

**Comment by czotomo** [comment]
@maxcountryman
btw, maybe Squash and Merge would keep the history a little bit cleaner on main branch? I, for example, sometimes produce 'wip'-style commits which are not really bringing anything to the commit history 😅

**Comment by czotomo** [comment]
@maxcountryman 
do you want these integrations tests to be run in CI?
If yes, using docker compose or individually configured database servers?

**Comment by maxcountryman** [comment]
Ideally, yes. I don't have a strong preference but Compose sounds easier to maintain.

**Review by maxcountryman — APPROVED** [review]
Beautiful 😻

**Pull request merged**
